<<<<<<< HEAD
name: Deploy Node.js App to VPS
=======
name: Deploy to VPS
>>>>>>> main

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # deploy only from main branch
=======
      - main
>>>>>>> main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout code
        uses: actions/checkout@v3

=======
>>>>>>> main
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
<<<<<<< HEAD
          port: 22
          script: |
            set -e
            echo "ðŸš€ Starting deploy..."
            cd /home/dev-jean/htdocs/students-api
=======
          script: |
            set -e
            cd /var/www/node-api-automation-students
>>>>>>> main
            git pull origin main
            npm ci
            pm2 restart students-api || pm2 start src/server.js --name students-api
            pm2 save
<<<<<<< HEAD
            echo "âœ… Deployment complete"
=======
>>>>>>> main
